// =====================================================================
//  REFERENTIELS DU BREVET : COMPETENCES, TAXONOMIES, REGLES, SOURCES
//
//  Une SEULE ecriture de ces donnees. `scripts/seed-brevet.mjs` les lit
//  pour produire `supabase/sql/43_brevet_referentiels.sql` et pour les
//  appliquer en base ; les tests hors ligne les lisent aussi, de sorte que
//  ce qui est teste est ce qui est reellement pose.
//
//  DEUX MATIERES, DEUX MONDES
//  --------------------------
//  La cle primaire des deux tables cibles est (matiere, code) :
//  `bareme_verifier` / `brevet_verifier` refusent une competence ou
//  signalent un code absent du referentiel de CETTE matiere-la. Une regle
//  de francais ne peut donc pas atteindre une copie de mathematiques.
//
//  LES COMPETENCES DU FRANCAIS
//  ---------------------------
//  Reprises de la note de service, qui enonce les quatre attendus de
//  l'epreuve : « lire », « ecrire », « comprendre le fonctionnement de la
//  langue » et avoir acquis « des elements de culture litteraire et
//  artistique ». On y ajoute deux aspects evalues seulement quand le sujet
//  les mobilise : l'analyse de l'image, et la reecriture.
//
//  LES COMPETENCES DES MATHEMATIQUES
//  ---------------------------------
//  Les six competences citees mot pour mot par la note de service :
//  chercher, modeliser, representer, raisonner, calculer, communiquer.
//
//  LA GRAVITE NE RETIRE RIEN
//  -------------------------
//  Elle est PEDAGOGIQUE. L'effet sur la note vient du bareme du sujet, ou
//  de `penalite_defaut` / `regle_retrait` quand l'administratrice l'a
//  explicitement renseigne. Un code sans penalite est purement explicatif.
// =====================================================================

export const VERSION_REFERENTIELS = '1.0.0';

/* ------------------------------------------------------------------ */
/*  1. Competences                                                    */
/* ------------------------------------------------------------------ */

export const COMPETENCES = [
  // --- Francais -----------------------------------------------------
  { matiere: 'brevet_francais', code: 'lire', libelle: 'Lire', ordre: 1, toujours_mobilisee: true,
    description: "Comprendre un texte litteraire, prelever une information explicite, degager le sens global, interpreter ce qui n'est pas dit." },
  { matiere: 'brevet_francais', code: 'ecrire', libelle: 'Ecrire', ordre: 2, toujours_mobilisee: true,
    description: 'Produire un texte coherent et construit, adapte a la consigne, en respectant les normes de la langue ecrite.' },
  { matiere: 'brevet_francais', code: 'langue', libelle: 'Comprendre le fonctionnement de la langue', ordre: 3, toujours_mobilisee: true,
    description: 'Identifier natures et fonctions, analyser propositions et subordination, maitriser temps, modes et accords, manipuler la langue.' },
  { matiere: 'brevet_francais', code: 'culture', libelle: 'Culture litteraire et artistique', ordre: 4, toujours_mobilisee: true,
    description: "Mobiliser des reperes litteraires et artistiques, reconnaitre un genre, un procede, un effet, situer un texte dans son contexte." },
  { matiere: 'brevet_francais', code: 'image', libelle: 'Analyse de l\'image', ordre: 5, toujours_mobilisee: false,
    description: "Evaluee UNIQUEMENT si le sujet comporte une image. Sinon 'non_applicable', jamais zero." },
  { matiere: 'brevet_francais', code: 'reecriture', libelle: 'Reecriture', ordre: 6, toujours_mobilisee: false,
    description: "Transformer des formes selon une consigne (temps, enonciation, personne, genre, nombre). Evaluee seulement si le sujet comporte l'exercice." },

  // --- Mathematiques ------------------------------------------------
  { matiere: 'brevet_mathematiques', code: 'chercher', libelle: 'Chercher', ordre: 1, toujours_mobilisee: true,
    description: "S'engager dans une recherche : extraire l'information utile, tester un cas particulier, essayer, reformuler la question." },
  { matiere: 'brevet_mathematiques', code: 'modeliser', libelle: 'Modeliser', ordre: 2, toujours_mobilisee: true,
    description: 'Traduire une situation concrete en objet mathematique (equation, fonction, configuration, modele de probabilite) et revenir au concret pour interpreter.' },
  { matiere: 'brevet_mathematiques', code: 'representer', libelle: 'Representer', ordre: 3, toujours_mobilisee: true,
    description: 'Choisir un registre adapte : figure, graphique, tableau, arbre, ecriture algebrique, et passer de l\'un a l\'autre.' },
  { matiere: 'brevet_mathematiques', code: 'raisonner', libelle: 'Raisonner', ordre: 4, toujours_mobilisee: true,
    description: 'Poser les hypotheses, nommer la propriete employee, verifier ses conditions, enchainer les deductions, conclure. C\'est la demonstration qui est notee, pas le resultat seul.' },
  { matiere: 'brevet_mathematiques', code: 'calculer', libelle: 'Calculer', ordre: 5, toujours_mobilisee: true,
    description: 'Mener un calcul exact ou approche, controler l\'ordre de grandeur, respecter l\'arrondi et l\'unite demandes.' },
  { matiere: 'brevet_mathematiques', code: 'communiquer', libelle: 'Communiquer', ordre: 6, toujours_mobilisee: true,
    description: 'Rediger clairement, employer le vocabulaire et les notations justes, enoncer le resultat en phrase et le replacer dans le contexte.' },
];

/* ------------------------------------------------------------------ */
/*  2. Taxonomie du francais                                          */
/* ------------------------------------------------------------------ */

const SRC_FR = 'Programme de francais du cycle 4 et note de service NOR MENE2515977N';

function fr(code, partie, categorie, sous, libelle, explication, gravite, conseil, competence, extra = {}) {
  return {
    matiere: 'brevet_francais',
    code, partie, categorie,
    sous_categorie: sous,
    libelle_eleve: libelle,
    explication,
    gravite,
    penalite_defaut: extra.penalite ?? null,
    regle_application: extra.regle ?? null,
    plafond_perte: extra.plafond ?? null,
    cumul_autorise: extra.cumul ?? false,
    points_partiels_possibles: extra.partiels ?? true,
    exemple: extra.exemple ?? null,
    conseil,
    competence,
    nature: extra.nature ?? 'eleve',
    source: extra.source ?? SRC_FR,
    version: VERSION_REFERENTIELS,
  };
}

export const TAXONOMIE_FRANCAIS = [
  // --- Comprehension et interpretation ------------------------------
  fr('FR-COMP-01', 'texte', 'comprehension', 'sens litteral', 'Tu n\'as pas compris ce que dit le texte',
     "La reponse contredit ce que le texte affirme explicitement.", 'majeure',
     'Relis la phrase du texte qui contient la reponse, et reformule-la avec tes mots avant de repondre.', 'lire'),
  fr('FR-COMP-02', 'texte', 'comprehension', 'prelevement', 'Tu as cherche la reponse au mauvais endroit',
     "L'information prelevee vient d'un autre passage que celui que la question vise.", 'moderee',
     'Repere le mot de la question dans le texte : la reponse est presque toujours juste autour.', 'lire'),
  fr('FR-COMP-03', 'texte', 'comprehension', 'globale', 'Tu as compris un detail mais pas l\'ensemble',
     'La reponse est exacte sur un point mais manque le sens general demande.', 'moderee',
     'Avant de repondre a une question globale, resume le texte en une phrase.', 'lire'),
  fr('FR-INT-01', 'texte', 'interpretation', 'implicite', 'Tu es reste a ce qui est ecrit',
     "La question demandait d'interpreter, la reponse se contente de reciter le texte.", 'moderee',
     'Demande-toi pourquoi l\'auteur ecrit cela, pas seulement ce qu\'il ecrit.', 'lire'),
  fr('FR-INT-02', 'texte', 'interpretation', 'sur-interpretation', 'Tu as invente ce que le texte ne dit pas',
     'L\'interpretation ne s\'appuie sur aucun element du texte.', 'moderee',
     'Chaque idee que tu avances doit pouvoir etre reliee a un mot precis du texte.', 'lire'),
  fr('FR-INT-03', 'texte', 'interpretation', 'defendable non prevue', 'Interpretation possible mais non prevue au corrige',
     "Lecture cohérente et etayee que le corrige n'avait pas anticipee.", 'mineure',
     'Continue a justifier tes lectures : celle-ci se defend.', 'lire',
     { nature: 'sujet', regle: 'Ne jamais mettre zero : declencher une validation humaine.' }),
  fr('FR-JUST-01', 'texte', 'justification', 'absente', 'Tu as donne la bonne idee sans la justifier',
     'La reponse est juste mais le texte n\'est pas convoque comme le barème l\'exige.', 'moderee',
     'Ajoute « parce que » suivi d\'une courte citation.', 'lire', { partiels: true }),
  fr('FR-JUST-02', 'texte', 'justification', 'hors propos', 'Ta justification ne prouve pas ce que tu affirmes',
     'La citation retenue ne soutient pas l\'affirmation.', 'moderee',
     'Verifie que ta citation contient bien le mot qui prouve ton idee.', 'lire'),
  fr('FR-CIT-01', 'texte', 'citation', 'absente', 'Il manque la citation demandee',
     'Le barème exigeait une citation du texte, aucune n\'est presente.', 'moderee',
     'Recopie entre guillemets le groupe de mots exact du texte.', 'lire'),
  fr('FR-CIT-02', 'texte', 'citation', 'non expliquee', 'Tu cites sans expliquer',
     'La citation est juste mais rien n\'est dit de ce qu\'elle prouve.', 'moderee',
     'Apres chaque citation, ecris une phrase qui dit ce qu\'elle montre.', 'lire'),
  fr('FR-CIT-03', 'texte', 'citation', 'inexacte', 'Ta citation ne correspond pas au texte',
     'Les mots cites ne figurent pas tels quels dans le texte.', 'mineure',
     'Recopie mot pour mot, sans reformuler, entre guillemets.', 'lire'),
  fr('FR-STYL-01', 'texte', 'analyse_stylistique', 'procede non identifie', 'Tu n\'as pas nomme le procede',
     'Le procede attendu (comparaison, metaphore, hyperbole, personnification, gradation...) n\'est pas identifie.', 'moderee',
     'Apprends cinq figures et leur definition : elles reviennent a chaque brevet.', 'culture'),
  fr('FR-STYL-02', 'texte', 'analyse_stylistique', 'effet non explique', 'Tu nommes le procede sans dire ce qu\'il produit',
     'La figure est identifiee mais son effet sur le lecteur n\'est pas explique.', 'moderee',
     'Termine toujours par « ce qui donne l\'impression que… ».', 'culture'),
  fr('FR-IMG-01', 'texte', 'interpretation', 'image', 'Tu n\'as pas mis l\'image en relation avec le texte',
     'La question portait sur le lien entre l\'image et le texte, la reponse ne parle que de l\'un des deux.', 'moderee',
     'Decris d\'abord ce que tu vois, puis dis ce que cela rappelle du texte.', 'image'),
  fr('FR-LEX-01', 'texte', 'lexique', 'sens du mot', 'Le sens que tu donnes au mot n\'est pas celui du texte',
     'Le mot est compris hors de son contexte.', 'moderee',
     'Remplace le mot par ta definition dans la phrase : si la phrase ne veut plus rien dire, ce n\'est pas le bon sens.', 'langue'),
  fr('FR-LEX-02', 'texte', 'lexique', 'synonymie', 'Le synonyme propose ne convient pas ici',
     'Le mot propose a un sens voisin mais ne fonctionne pas dans la phrase.', 'mineure',
     'Verifie que ton synonyme garde la meme classe grammaticale et le meme registre.', 'langue'),
  fr('FR-LEX-03', 'texte', 'lexique', 'formation des mots', 'Tu n\'as pas reconnu le radical, le prefixe ou le suffixe',
     'La decomposition du mot est erronee.', 'mineure',
     'Cherche un mot de la meme famille que tu connais bien.', 'langue'),

  // --- Grammaire ----------------------------------------------------
  fr('FR-GRAM-01', 'texte', 'grammaire', 'nature', 'Tu as confondu la nature du mot',
     'La classe grammaticale annoncee n\'est pas la bonne.', 'moderee',
     'La nature ne change jamais : nom, verbe, adjectif, pronom, determinant, adverbe, preposition, conjonction.', 'langue'),
  fr('FR-GRAM-02', 'texte', 'grammaire', 'fonction', 'Tu as confondu la fonction du mot',
     'La fonction annoncee ne correspond pas au role du mot dans la phrase.', 'moderee',
     'La fonction depend de la phrase : pose la question « qui ? quoi ? a qui ? » au verbe.', 'langue'),
  fr('FR-GRAM-03', 'texte', 'grammaire', 'proposition', 'Le decoupage en propositions est faux',
     'Le nombre ou les limites des propositions sont errones.', 'moderee',
     'Compte les verbes conjugues : autant de verbes, autant de propositions.', 'langue'),
  fr('FR-GRAM-04', 'texte', 'grammaire', 'subordination', 'La subordonnee n\'est pas correctement identifiee',
     'La nature de la subordonnee (relative, conjonctive, interrogative indirecte) est erronee.', 'moderee',
     'Regarde le mot qui l\'introduit : « qui / que / dont / ou » = relative, « que » apres un verbe = conjonctive.', 'langue'),
  fr('FR-CONJ-01', 'texte', 'conjugaison', 'temps et modes', 'Le temps ou le mode annonce est faux',
     'Le temps, le mode ou la personne identifies ne sont pas ceux du verbe.', 'moderee',
     'Recite la conjugaison complete du verbe : la terminaison te donne le temps.', 'langue'),
  fr('FR-CONJ-02', 'texte', 'conjugaison', 'valeur des temps', 'Tu n\'as pas explique la valeur du temps',
     'Le temps est bien identifie mais sa valeur (action de premier plan, arriere-plan, habitude, verite generale) n\'est pas donnee.', 'moderee',
     'Imparfait = decor ou habitude ; passe simple = action qui avance le recit.', 'langue'),
  fr('FR-ACC-01', 'toutes', 'orthographe_grammaticale', 'accord sujet-verbe', 'Le verbe n\'est pas accorde avec son sujet',
     'La marque de personne ou de nombre du verbe est erronee.', 'moderee',
     'Encadre le sujet, pose la question « qui est-ce qui ? » avant le verbe.', 'langue'),
  fr('FR-ACC-02', 'toutes', 'orthographe_grammaticale', 'accord dans le groupe nominal', 'L\'accord dans le groupe nominal est faux',
     'Le determinant, le nom et l\'adjectif ne s\'accordent pas.', 'moderee',
     'Repere le nom noyau, puis accorde tout ce qui l\'entoure.', 'langue'),
  fr('FR-ACC-03', 'toutes', 'orthographe_grammaticale', 'participe passe', 'L\'accord du participe passe est faux',
     'La regle d\'accord avec etre, avoir ou le COD antepose n\'est pas appliquee.', 'moderee',
     'Avec « etre », on accorde avec le sujet ; avec « avoir », seulement si le COD est avant.', 'langue'),
  fr('FR-ORTH-01', 'toutes', 'orthographe_lexicale', 'orthographe d\'usage', 'Le mot n\'est pas ecrit correctement',
     'Orthographe lexicale erronee, hors accord et hors conjugaison.', 'mineure',
     'Note les mots que tu rates dans un carnet et relis-le avant l\'epreuve.', 'ecrire'),
  fr('FR-ORTH-02', 'toutes', 'orthographe_grammaticale', 'homophone', 'Tu as confondu deux homophones',
     'Confusion entre a/a, et/est, ou/ou, ce/se, ces/ses, on/ont, son/sont, la/la/l\'a.', 'moderee',
     'Remplace par un autre temps ou une autre personne : « il a » devient « il avait ».', 'langue'),
  fr('FR-SYNT-01', 'toutes', 'syntaxe', 'phrase incorrecte', 'Ta phrase n\'est pas construite correctement',
     'Phrase sans verbe, sans sujet, ou dont la construction rend le sens incertain.', 'moderee',
     'Relis chaque phrase a voix basse : si tu manques d\'air, coupe-la en deux.', 'ecrire'),
  fr('FR-SYNT-02', 'toutes', 'syntaxe', 'oral a l\'ecrit', 'Tu ecris comme tu parles',
     'Tournure orale, negation incomplete, familiarite deplacee a l\'ecrit.', 'mineure',
     'La negation ecrite se dit toujours en deux mots : « ne… pas ».', 'ecrire'),
  fr('FR-PONC-01', 'toutes', 'ponctuation', 'absente ou fautive', 'La ponctuation manque ou est mal placee',
     'Absence de point, de virgule utile, ou ponctuation du dialogue erronee.', 'mineure',
     'Un point a la fin de chaque idee, une majuscule apres.', 'ecrire'),

  // --- Reecriture ---------------------------------------------------
  fr('REEC-TRANSFO', 'reecriture', 'reecriture', 'transformation', 'La transformation demandee n\'est pas faite',
     "La forme n'a pas ete modifiee, ou l'a ete autrement que ce que la consigne demandait.", 'majeure',
     'Souligne d\'abord toutes les formes a changer, puis change-les une par une.', 'reecriture',
     { regle: 'Une forme dont la transformation est manquee n\'est jamais penalisee une seconde fois au titre de la copie.' }),
  fr('REEC-COPIE', 'reecriture', 'reecriture', 'erreur de copie', 'Erreur de copie sur un mot qui ne devait pas changer',
     "Erreur de pure copie, ne portant pas sur une forme a modifier. La note de service prevoit pour elle un bareme specifique, propre au sujet.", 'mineure',
     'Recopie le passage mot pour mot, puis relis en pointant chaque mot du doigt.', 'ecrire',
     { regle: 'Penalite uniquement si le bareme du sujet la renseigne ; jamais cumulee avec REEC-TRANSFO sur la meme forme.' }),
  fr('REEC-ABSENTE', 'reecriture', 'absence_de_reponse', null, 'Forme non recopiee',
     'La forme attendue est absente de la copie.', 'moderee',
     'Verifie que tu as bien recopie tout le passage demande.', 'reecriture'),

  // --- Dictee -------------------------------------------------------
  fr('DICT-ACCORD', 'dictee', 'dictee', 'accord', 'Erreur d\'accord dans la dictee',
     'Marque de genre, de nombre ou de participe passe erronee.', 'moderee',
     'A la relecture, cherche les sujets et accorde les verbes, puis les noms et leurs adjectifs.', 'langue'),
  fr('DICT-CONJ', 'dictee', 'dictee', 'conjugaison', 'Erreur de conjugaison dans la dictee',
     'Terminaison verbale erronee (temps, personne, mode).', 'moderee',
     'Repere le temps du recit avant d\'ecrire : il ne change presque jamais en cours de dictee.', 'langue'),
  fr('DICT-HOMO', 'dictee', 'dictee', 'homophone', 'Homophone confondu dans la dictee',
     'Deux mots qui se prononcent pareil ont ete confondus.', 'moderee',
     'Apprends trois tests de remplacement : ils suffisent pour la plupart des homophones.', 'langue'),
  fr('DICT-LEX', 'dictee', 'dictee', 'lexique', 'Mot mal orthographie dans la dictee',
     'Orthographe lexicale erronee.', 'mineure',
     'Si tu hesites sur un mot, ecris-le, continue, et reviens dessus a la relecture.', 'ecrire'),
  fr('DICT-ACCENT', 'dictee', 'dictee', 'accent', 'Accent oublie ou mal choisi',
     'Accent absent, en trop, ou du mauvais type.', 'mineure',
     'Relis en cherchant uniquement les accents : une relecture, un seul objectif.', 'ecrire'),
  fr('DICT-MAJ', 'dictee', 'dictee', 'majuscule', 'Majuscule oubliee ou mal placee',
     'Majuscule absente en debut de phrase ou sur un nom propre, ou majuscule en trop.', 'mineure',
     'Apres chaque point, une majuscule. Sans exception.', 'ecrire'),
  fr('DICT-PONC', 'dictee', 'dictee', 'ponctuation', 'Ponctuation de la dictee erronee',
     'Signe de ponctuation absent, en trop, ou different de celui qui a ete dicte.', 'mineure',
     'Ecoute les pauses de la voix : elles indiquent les virgules et les points.', 'ecrire'),
  fr('DICT-OUBLI', 'dictee', 'dictee', 'mot oublie', 'Un mot du texte manque',
     'Un mot dicte n\'a pas ete ecrit.', 'moderee',
     'A la relecture finale, verifie que chaque phrase a bien un sens complet.', 'ecrire'),
  fr('DICT-AJOUT', 'dictee', 'dictee', 'mot ajoute', 'Un mot en trop',
     'Un mot absent du texte dicte a ete ecrit.', 'mineure',
     'N\'ajoute rien qui « sonne bien » : ecris seulement ce que tu entends.', 'ecrire'),
  fr('DICT-SEGM', 'dictee', 'dictee', 'segmentation', 'Deux mots colles ou un mot coupe',
     'Decoupage des mots errone.', 'mineure',
     'Verifie les petits mots : « d\'abord », « a peine », « quelque temps ».', 'ecrire'),
  fr('DICT-TRAIT', 'dictee', 'dictee', 'trait d\'union', 'Trait d\'union oublie ou en trop',
     'Trait d\'union absent ou ajoute a tort.', 'mineure',
     'Les nombres composes et les verbes inverses prennent un trait d\'union.', 'ecrire'),
  fr('DICT-APOS', 'dictee', 'dictee', 'apostrophe', 'Apostrophe oubliee ou en trop',
     'Elision absente ou ajoutee a tort.', 'mineure',
     'Devant une voyelle, « le » devient « l\' » : c\'est presque toujours automatique.', 'ecrire'),
  fr('DICT-RECT', 'dictee', 'dictee', 'graphie rectifiee', 'Graphie de l\'orthographe rectifiee',
     "Graphie issue des rectifications orthographiques. Admise si le bareme du sujet la mentionne.", 'mineure',
     'Cette graphie est acceptee : rien a corriger.', 'ecrire',
     { nature: 'sujet', regle: 'Aucune penalite si la graphie figure dans les graphies admises du sujet.' }),
  fr('DICT-OCR', 'dictee', 'reconnaissance_incertaine', 'decalage de transcription', 'Lecture incertaine de la dictee',
     "Ecart probablement du a la lecture de l'ecriture manuscrite, pas a une faute.", 'mineure',
     null, null,
     { nature: 'reconnaissance', regle: 'Aucune penalite. Declenche une validation humaine bloquante si la note en depend.' }),

  // --- Redaction ----------------------------------------------------
  fr('FR-CONS-01', 'redaction', 'respect_de_la_consigne', 'consigne', 'Tu n\'as pas respecte tout ce que demandait le sujet',
     'Une contrainte explicite du sujet n\'est pas respectee.', 'majeure',
     'Souligne chaque contrainte du sujet et coche-la quand tu l\'as traitee.', 'ecrire'),
  fr('FR-CONS-02', 'redaction', 'respect_de_la_consigne', 'enonciation', 'Tu n\'as pas garde la bonne situation d\'enonciation',
     'Le narrateur, le temps ou le destinataire imposes ne sont pas tenus.', 'moderee',
     'Ecris en haut de ton brouillon : « je / il », « passe / present ». Verifie a chaque paragraphe.', 'ecrire'),
  fr('FR-CONS-03', 'redaction', 'respect_de_la_consigne', 'longueur', 'Ton texte est trop court',
     'La longueur minimale annoncee par le sujet n\'est pas atteinte.', 'moderee',
     'Compte tes lignes a mi-parcours : il te reste le temps d\'en ajouter.', 'ecrire',
     { regle: 'La perte se fait par le critere « longueur » de la grille, jamais par un retrait supplementaire.' }),
  fr('FR-COH-01', 'redaction', 'coherence', 'contradiction', 'Ton texte se contredit',
     'Deux elements du texte sont incompatibles.', 'moderee',
     'Relis en te demandant : est-ce que tout cela peut arriver au meme personnage ?', 'ecrire'),
  fr('FR-COH-02', 'redaction', 'coherence', 'texte support', 'Ton texte ne colle pas au texte de depart',
     'La suite ou la reponse contredit le texte support.', 'moderee',
     'Relis les cinq dernieres lignes du texte avant de commencer a ecrire.', 'lire'),
  fr('FR-ORG-01', 'redaction', 'organisation', 'paragraphes', 'Ton texte n\'est pas organise en paragraphes',
     'Absence de decoupage, ou decoupage qui ne suit pas les idees.', 'moderee',
     'Une idee, un paragraphe. Va a la ligne et decale la premiere ligne.', 'ecrire'),
  fr('FR-ORG-02', 'redaction', 'organisation', 'connecteurs', 'Tes idees ne sont pas reliees',
     'Absence de connecteurs logiques ou temporels.', 'mineure',
     'Apprends six connecteurs : d\'abord, ensuite, de plus, cependant, car, donc.', 'ecrire'),
  fr('FR-ARG-01', 'redaction', 'argumentation', 'argument absent', 'Tu donnes ton avis sans argument',
     'Une opinion est avancee sans raison qui la soutienne.', 'majeure',
     'Apres chaque avis, ecris « parce que » et complete.', 'ecrire'),
  fr('FR-ARG-02', 'redaction', 'argumentation', 'argument non developpe', 'Ton argument n\'est pas developpe',
     'L\'argument tient en une phrase et n\'est pas explique.', 'moderee',
     'Un argument = une affirmation + une explication + un exemple.', 'ecrire'),
  fr('FR-EX-01', 'redaction', 'exemples', 'absent', 'Il manque des exemples',
     'Aucun exemple ne vient appuyer les arguments.', 'moderee',
     'Prends tes exemples dans tes lectures, tes cours, ou ta vie : les trois comptent.', 'culture'),
  fr('FR-EX-02', 'redaction', 'exemples', 'non relie', 'Ton exemple ne prouve pas ton idee',
     'L\'exemple est present mais son lien avec l\'argument n\'est pas explicite.', 'moderee',
     'Termine ton exemple par « ce qui montre que… ».', 'ecrire'),
  fr('FR-EXP-01', 'redaction', 'expression', 'vocabulaire', 'Ton vocabulaire reste tres general',
     'Emploi repete de mots passe-partout la ou un mot precis etait possible.', 'mineure',
     'Remplace « chose », « truc », « faire » par un mot precis a chaque relecture.', 'ecrire'),
  fr('FR-EXP-02', 'redaction', 'expression', 'repetition', 'Tu repetes les memes mots',
     'Repetitions evitables.', 'mineure',
     'Utilise des pronoms et des synonymes pour ne pas repeter le nom du personnage.', 'ecrire'),

  // --- Transversaux -------------------------------------------------
  fr('FR-HS-01', 'toutes', 'hors_sujet', null, 'Ta reponse ne repond pas a la question posee',
     'La reponse porte sur autre chose que ce qui est demande.', 'majeure',
     'Recopie mentalement la question avant de repondre, et verifie que ta phrase y repond.', 'lire'),
  fr('FR-INC-01', 'toutes', 'reponse_incomplete', null, 'Ta reponse est commencee mais pas finie',
     'Une partie de ce qui etait attendu manque.', 'moderee',
     'Compte ce que la question demande : « deux raisons » veut dire deux.', 'lire'),
  fr('FR-ABS-01', 'toutes', 'absence_de_reponse', null, 'Tu n\'as pas repondu',
     'Aucune reponse n\'est ecrite.', 'majeure',
     'Ecris toujours quelque chose : une reponse partielle rapporte souvent des points.', null),
  fr('FR-ILL-01', 'toutes', 'illisibilite', null, 'Reponse illisible',
     "L'ecriture ne permet pas de lire la reponse. Ce n'est PAS une absence de reponse.", 'mineure',
     'Prends le temps de former tes lettres : une reponse juste mais illisible ne rapporte rien.', null,
     { nature: 'reconnaissance', regle: 'Aucune penalite automatique. Validation humaine bloquante.' }),
  fr('FR-OCR-01', 'toutes', 'reconnaissance_incertaine', null, 'Lecture incertaine',
     "Le systeme n'est pas sur d'avoir bien lu ce passage.", 'mineure', null, null,
     { nature: 'reconnaissance', regle: 'Aucune penalite. Validation humaine.' }),
  fr('FR-SUJET-01', 'toutes', 'reponse_incomplete', 'anomalie du sujet', 'Anomalie du sujet ou du corrige',
     'Le sujet, le corrige et le bareme ne concordent pas.', 'majeure', null, null,
     { nature: 'sujet', regle: 'Validation humaine bloquante. Aucune consequence pour l\'eleve.' }),
];

/* ------------------------------------------------------------------ */
/*  3. Taxonomie des mathematiques                                    */
/* ------------------------------------------------------------------ */

const SRC_MA =
  'Programme de mathematiques du cycle 4, note de service NOR MENE2515977N et liste indicative d\'automatismes (octobre 2025)';

function ma(code, partie, categorie, sous, libelle, explication, gravite, conseil, competence, extra = {}) {
  return {
    matiere: 'brevet_mathematiques',
    code, partie, categorie,
    sous_categorie: sous,
    libelle_eleve: libelle,
    explication,
    gravite,
    penalite_defaut: extra.penalite ?? null,
    regle_application: extra.regle ?? null,
    plafond_perte: extra.plafond ?? null,
    cumul_autorise: extra.cumul ?? false,
    points_partiels_possibles: extra.partiels ?? true,
    exemple: extra.exemple ?? null,
    conseil,
    competence,
    nature: extra.nature ?? 'eleve',
    source: extra.source ?? SRC_MA,
    version: VERSION_REFERENTIELS,
  };
}

export const TAXONOMIE_MATHS = [
  ma('MA-CONS-01', 'toutes', 'comprehension_consigne', null, 'Tu n\'as pas repondu a la question posee',
     "La reponse porte sur autre chose que ce que l'enonce demande.", 'majeure',
     'Souligne la question dans l\'enonce, et verifie a la fin que ta phrase de conclusion y repond.', 'chercher'),
  ma('MA-METH-01', 'raisonnement', 'choix_de_methode', null, 'La methode choisie ne convient pas',
     'La propriete ou l\'outil retenu ne s\'applique pas a cette situation.', 'majeure',
     'Avant de calculer, ecris ce que tu cherches et ce que tu connais : la methode s\'impose souvent d\'elle-meme.', 'modeliser'),
  ma('MA-METH-02', 'raisonnement', 'choix_de_methode', 'alternative valide', 'Methode differente du corrige mais valide',
     "Demarche mathematiquement correcte que le corrige n'avait pas prevue.", 'mineure',
     'Ta methode fonctionne : continue a la rediger clairement.', 'chercher',
     { nature: 'sujet', regle: 'Jamais zero d\'office. Validation humaine, et points a la hauteur de la demarche.' }),
  ma('MA-RAIS-01', 'raisonnement', 'raisonnement', 'enchainement', 'Ton raisonnement saute une etape',
     'Une deduction est posee sans que ce qui la justifie soit ecrit.', 'moderee',
     'Ecris chaque etape, meme celles qui te semblent evidentes : ce sont elles qui rapportent les points.', 'raisonner'),
  ma('MA-RAIS-02', 'raisonnement', 'raisonnement', 'conclusion sans preuve', 'Tu conclus sans avoir demontre',
     'La conclusion est juste mais rien ne l\'etablit.', 'majeure',
     'Une conclusion correcte sans demonstration ne vaut pas une demonstration.', 'raisonner'),
  ma('MA-RAIS-03', 'raisonnement', 'raisonnement', 'exemple pris pour preuve', 'Un exemple ne demontre pas',
     'Un cas particulier est presente comme une preuve generale.', 'moderee',
     'Un exemple peut illustrer, jamais demontrer. Un contre-exemple, lui, suffit a refuter.', 'raisonner'),
  ma('MA-CALC-01', 'toutes', 'calcul_numerique', null, 'Erreur de calcul',
     'Erreur dans un calcul numerique, sans erreur de methode.', 'mineure',
     'Refais le calcul de tete pour verifier l\'ordre de grandeur.', 'calculer',
     { regle: 'Une erreur de calcul isolee laisse intacts les points de raisonnement.' }),
  ma('MA-CALC-02', 'toutes', 'calcul_numerique', 'priorites', 'Les priorites operatoires ne sont pas respectees',
     'Multiplication, division, parentheses ou puissances traitees dans le mauvais ordre.', 'moderee',
     'Parentheses, puis puissances, puis multiplications et divisions, puis additions et soustractions.', 'calculer'),
  ma('MA-LIT-01', 'toutes', 'calcul_litteral', 'developpement', 'Erreur de developpement',
     'Distributivite mal appliquee.', 'moderee',
     'Multiplie chaque terme de la premiere parenthese par chaque terme de la seconde, sans en oublier.', 'calculer'),
  ma('MA-LIT-02', 'toutes', 'calcul_litteral', 'factorisation', 'Erreur de factorisation',
     'Facteur commun mal identifie ou identite remarquable mal employee.', 'moderee',
     'Cherche ce qui apparait dans TOUS les termes.', 'calculer'),
  ma('MA-LIT-03', 'raisonnement', 'calcul_litteral', 'equation', 'Erreur de resolution d\'equation',
     'Operation appliquee a un seul membre, ou changement de signe oublie.', 'moderee',
     'Ce que tu fais d\'un cote, fais-le de l\'autre. Toujours.', 'calculer'),
  ma('MA-FRAC-01', 'toutes', 'fraction', null, 'Erreur sur les fractions',
     'Denominateur commun, simplification ou operation sur les fractions erronee.', 'moderee',
     'Pour additionner, meme denominateur ; pour multiplier, non.', 'calculer'),
  ma('MA-PUIS-01', 'toutes', 'puissance', null, 'Erreur sur les puissances',
     'Regle de calcul sur les puissances ou notation scientifique erronee.', 'moderee',
     'Meme base : on additionne les exposants pour un produit.', 'calculer'),
  ma('MA-PROP-01', 'toutes', 'proportionnalite', null, 'Erreur de proportionnalite',
     'Situation traitee comme proportionnelle alors qu\'elle ne l\'est pas, ou coefficient errone.', 'moderee',
     'Verifie d\'abord que le rapport est constant, puis seulement applique la regle.', 'modeliser'),
  ma('MA-POUR-01', 'toutes', 'pourcentage', null, 'Erreur de pourcentage',
     'Augmentation, diminution ou pourcentage d\'un nombre mal calcule.', 'moderee',
     'Augmenter de 20 %, c\'est multiplier par 1,2. Diminuer de 20 %, c\'est multiplier par 0,8.', 'calculer'),
  ma('MA-FONC-01', 'raisonnement', 'fonction', null, 'Erreur sur les fonctions',
     'Image et antecedent confondus, ou expression de la fonction mal utilisee.', 'moderee',
     'f(3) = 7 se lit : l\'image de 3 est 7, l\'antecedent de 7 est 3.', 'representer'),
  ma('MA-GRAPH-01', 'toutes', 'graphique', null, 'Erreur de lecture graphique',
     'Lecture d\'abscisse ou d\'ordonnee erronee, ou echelle non prise en compte.', 'moderee',
     'Trace au crayon les pointilles jusqu\'aux axes avant de lire.', 'representer'),
  ma('MA-STAT-01', 'toutes', 'statistique', null, 'Erreur sur les statistiques',
     'Moyenne, mediane, etendue ou frequence mal calculee ou mal interpretee.', 'moderee',
     'La mediane se lit sur la serie ORDONNEE : range les valeurs d\'abord.', 'calculer'),
  ma('MA-PROBA-01', 'toutes', 'probabilite', null, 'Erreur de probabilite',
     'Issues mal denombrees, ou probabilite hors de l\'intervalle [0 ; 1].', 'moderee',
     'Compte les cas favorables, puis tous les cas possibles. Le resultat est toujours entre 0 et 1.', 'modeliser'),
  ma('MA-ARITH-01', 'toutes', 'arithmetique', null, 'Erreur d\'arithmetique',
     'Diviseurs, multiples, PGCD, nombres premiers ou criteres de divisibilite errones.', 'moderee',
     'Apprends les criteres de divisibilite par 2, 3, 5 et 9 : ils reviennent tout le temps.', 'calculer'),
  ma('MA-GEO-01', 'raisonnement', 'geometrie', 'hypotheses', 'Tu n\'as pas ecrit les hypotheses',
     'La propriete est employee sans que ses conditions d\'application soient verifiees.', 'moderee',
     'Ecris toujours : « Dans le triangle ABC rectangle en A… ».', 'raisonner'),
  ma('MA-GEO-02', 'raisonnement', 'theoreme', 'Pythagore', 'Erreur sur le theoreme de Pythagore',
     'Hypotenuse mal identifiee, egalite mal ecrite, ou reciproque confondue avec le theoreme direct.', 'moderee',
     'L\'hypotenuse est toujours le cote oppose a l\'angle droit, et le plus long.', 'raisonner'),
  ma('MA-GEO-03', 'raisonnement', 'theoreme', 'Thales', 'Erreur sur le theoreme de Thales',
     'Configuration non reconnue, rapports mal ecrits, ou reciproque confondue.', 'moderee',
     'Ecris les trois rapports dans le meme ordre : petit triangle sur grand triangle.', 'raisonner'),
  ma('MA-GEO-04', 'raisonnement', 'trigonometrie', null, 'Erreur de trigonometrie',
     'Rapport (cosinus, sinus, tangente) mal choisi, ou cote mal identifie.', 'moderee',
     'Cosinus = adjacent sur hypotenuse. Ecris les trois formules avant de choisir.', 'calculer'),
  ma('MA-GEO-05', 'toutes', 'aire', null, 'Erreur d\'aire',
     'Formule d\'aire erronee ou mal appliquee.', 'moderee',
     'Aire du triangle = base fois hauteur divise par 2. La hauteur est perpendiculaire a la base.', 'calculer'),
  ma('MA-GEO-06', 'toutes', 'volume', null, 'Erreur de volume',
     'Formule de volume erronee ou mal appliquee.', 'moderee',
     'Prisme et cylindre : aire de base fois hauteur. Pyramide et cone : le tiers.', 'calculer'),
  ma('MA-GEO-07', 'raisonnement', 'geometrie', 'transformation', 'Erreur sur une transformation',
     'Symetrie, translation, rotation ou homothetie mal construite ou mal identifiee.', 'moderee',
     'Une homothetie de rapport k multiplie les longueurs par k et les aires par k au carre.', 'representer'),
  ma('MA-GEO-08', 'raisonnement', 'geometrie', 'mesure sur la figure', 'Tu as mesure sur le dessin',
     "La reponse s'appuie sur une mesure prise sur la figure, qui n'est pas a l'echelle.", 'majeure',
     'Les figures ne sont pas a l\'echelle : ne mesure jamais, demontre.', 'raisonner'),
  ma('MA-UNIT-01', 'toutes', 'unite', 'absente', 'Il manque l\'unite',
     'Le resultat est donne sans unite alors que la question en attend une.', 'mineure',
     'Termine toujours par une phrase avec l\'unite : « L\'aire est de 24 cm². ».', 'communiquer',
     { regle: 'Une unite manquante ne se paie qu\'une fois, et pas une seconde fois dans les 2 points de redaction.' }),
  ma('MA-UNIT-02', 'toutes', 'unite', 'erronee', 'L\'unite n\'est pas la bonne',
     'Unite incoherente avec la grandeur calculee.', 'moderee',
     'Une longueur est en cm, une aire en cm², un volume en cm³.', 'communiquer'),
  ma('MA-CONV-01', 'toutes', 'conversion', null, 'Erreur de conversion',
     'Conversion d\'unites erronee.', 'moderee',
     'Pour les aires, chaque rang vaut 100 ; pour les volumes, 1000.', 'calculer'),
  ma('MA-ARR-01', 'toutes', 'arrondi', null, 'Erreur d\'arrondi',
     'Arrondi different de celui que le sujet demande.', 'mineure',
     'Relis la consigne : « au dixieme », « a l\'unite », « a 0,1 pres » ne veulent pas dire la meme chose.', 'calculer'),
  ma('MA-VAL-01', 'toutes', 'valeur_exacte', null, 'Valeur exacte attendue',
     'Le sujet demandait la valeur exacte, une valeur approchee a ete donnee.', 'moderee',
     'Valeur exacte = on garde la racine ou la fraction, on n\'utilise pas la calculatrice.', 'calculer'),
  ma('MA-VAL-02', 'toutes', 'valeur_approchee', null, 'Valeur approchee acceptable',
     'Valeur approchee donnee la ou le sujet l\'autorise.', 'mineure', null, 'calculer',
     { regle: 'Aucun retrait : le sujet l\'autorise.' }),
  ma('MA-ALGO-01', 'toutes', 'algorithmique', null, 'Erreur sur le programme ou l\'algorithme',
     'Sequence d\'instructions, boucle, condition ou variable mal interpretee.', 'moderee',
     'Deroule le programme pas a pas dans un tableau : une ligne par etape.', 'representer'),
  ma('MA-ALGO-02', 'toutes', 'algorithmique', 'bloc illisible', 'Bloc de programme illisible',
     "Une partie du script ou de la capture n'est pas lisible avec certitude.", 'mineure', null, null,
     { nature: 'reconnaissance', regle: 'Aucune penalite. Validation humaine.' }),
  ma('MA-DEM-01', 'raisonnement', 'demonstration', null, 'Ta demonstration est incomplete',
     'Une des etapes exigees (hypotheses, propriete, remplacement, calcul, unite, conclusion) manque.', 'moderee',
     'Six etapes : ce que je sais, la propriete, je remplace, je calcule, l\'unite, je conclus.', 'raisonner'),
  ma('MA-JUST-01', 'raisonnement', 'justification', null, 'Ta reponse n\'est pas justifiee',
     "Le resultat est donne sans justification, alors que le sujet impose de justifier sauf indication contraire.", 'moderee',
     'Ecris comment tu as trouve : c\'est la demarche qui rapporte le plus de points.', 'raisonner'),
  ma('MA-COM-01', 'toutes', 'communication', null, 'Ta redaction est difficile a suivre',
     'Calculs non presentes, etapes melangees, absence de phrase de conclusion.', 'mineure',
     'Une ligne par etape, un signe egal par ligne, une phrase pour conclure.', 'communiquer'),
  ma('MA-CASC-01', 'raisonnement', 'erreur_en_cascade', null, 'Consequence d\'une erreur precedente',
     "La reponse est fausse uniquement parce qu'elle reutilise un resultat faux obtenu plus haut, correctement exploite.", 'mineure',
     'Ta methode etait bonne : l\'erreur venait d\'avant.', 'raisonner',
     { nature: 'eleve',
       regle: 'Les points de methode sont CONSERVES. L\'erreur initiale ne se paie qu\'une fois.' }),
  ma('MA-INC-01', 'toutes', 'reponse_incomplete', null, 'Tu n\'as pas fini',
     'La demarche est engagee mais n\'aboutit pas.', 'mineure',
     'Meme inachevee, ecris ta demarche : les essais engages comptent.', 'chercher',
     { regle: 'Les essais et demarches engagees, meme non aboutis, doivent etre pris en compte (note de service).' }),
  ma('MA-ABS-01', 'toutes', 'absence_de_reponse', null, 'Tu n\'as rien ecrit',
     'Aucune trace de recherche.', 'majeure',
     'Ecris toujours ce que tu sais, meme sans finir : cela rapporte des points.', null),
  ma('MA-ILL-01', 'toutes', 'illisibilite', null, 'Ecriture illisible',
     "Le calcul ou le raisonnement ne peut pas etre lu. Ce n'est PAS une absence de reponse.", 'mineure',
     'Ecris tes chiffres lisiblement : un 1 qui ressemble a un 7 coute des points.', null,
     { nature: 'reconnaissance', regle: 'Aucune penalite automatique. Validation humaine bloquante.' }),
  ma('MA-OCR-01', 'toutes', 'reconnaissance_incertaine', null, 'Lecture incertaine',
     "Doute sur un signe, un exposant, un indice ou une fraction manuscrite.", 'mineure', null, null,
     { nature: 'reconnaissance', regle: 'Lecture la plus favorable a l\'eleve, puis validation humaine.' }),
  ma('MA-SUJET-01', 'toutes', 'reponse_incomplete', 'anomalie du sujet', 'Anomalie du sujet ou du corrige',
     'Le sujet, le corrige et le bareme ne concordent pas.', 'majeure', null, null,
     { nature: 'sujet', regle: 'Validation humaine bloquante. Aucune consequence pour l\'eleve.' }),
];

/* ------------------------------------------------------------------ */
/*  4. Sources officielles                                            */
/* ------------------------------------------------------------------ */

export const SOURCES_OFFICIELLES = [
  {
    code: 'BO_MENE2515977N',
    titre: "Modalites d'attribution du diplome national du brevet a compter de la session 2026",
    organisme: "Ministere de l'Education nationale — Bulletin officiel n° 33",
    url: 'https://www.education.gouv.fr/bo/2025/Hebdo33/MENE2515977N',
    date_publication: '2025-09-02',
    date_maj: '2025-09-04',
    date_consultation: '2026-08-08',
    session_concernee: 'a compter de 2026',
    statut: 'officiel',
    resume:
      "Note de service. Source primaire de toutes les regles chiffrees des deux epreuves : duree, bareme total, repartition des points, sujets au choix, calculatrice, prise en compte des essais, programme de reference a partir de 2027.",
  },
  {
    code: 'AUTOMATISMES_2025',
    titre:
      "Liste indicative d'automatismes susceptibles d'etre mobilises lors de l'epreuve ecrite de mathematiques (series generale et professionnelle)",
    organisme: "Ministere de l'Education nationale",
    url: 'https://www.education.gouv.fr/sites/default/files/2025-10/dnb-2026-liste-indicative-d-automatismes-susceptibles-d-tre-mobilis-s-lors-de-l-preuve-crite-de-math-matiques-s-ries-g-n-rale-et-professionnelle--442401.pdf',
    date_publication: '2025-10-01',
    date_maj: null,
    date_consultation: '2026-08-08',
    session_concernee: '2026 et suivantes',
    statut: 'officiel',
    resume:
      'Themes et intitules exacts des automatismes de la partie 1 : nombres et calculs, espace et geometrie, organisation et gestion de donnees et probabilites, proportionnalite et fonctions, algorithmique et programmation.',
  },
  {
    code: 'EDUSCOL_EPREUVES_DNB',
    titre: 'Les epreuves du DNB',
    organisme: 'Eduscol — Direction generale de l\'enseignement scolaire',
    url: 'https://eduscol.education.gouv.fr/5607/les-epreuves-du-dnb',
    date_publication: null,
    date_maj: null,
    date_consultation: '2026-08-08',
    session_concernee: '2026 et suivantes',
    statut: 'complementaire',
    resume:
      "Page de reference qui heberge les sujets zero. Non consultable automatiquement le 8 aout 2026 (protection anti-robot) : a ouvrir a la main pour recuperer les sujets zero de francais et de mathematiques.",
  },
  {
    code: 'SUJETS_ZERO_2026_SG',
    titre:
      'Sujets zero du DNB session 2026, serie generale : francais (grammaire et comprehension, dictee, redaction) et mathematiques (sujets A et B)',
    organisme: "Ministere de l'Education nationale - Eduscol",
    url: 'https://eduscol.education.gouv.fr/5607/les-epreuves-du-dnb',
    date_publication: '2025-12-05',
    date_maj: null,
    date_consultation: '2026-08-09',
    session_concernee: '2026',
    statut: 'officiel',
    resume:
      "Sujets zero officiels, lus integralement le 9 aout 2026. Ils attestent la structure reelle d'un sujet : en francais, comprehension 32 points + grammaire 18 points (dont reecriture 10) = 50, dictee 10, redaction 40 ; en mathematiques, 9 automatismes pour 6 points, et des exercices totalisant 12 points auxquels s'ajoutent les 2 points de redaction pour faire les 14 de la partie 2.",
  },
  {
    code: 'BO_PROGRAMMES_CYCLE4_2026',
    titre: "Programmes d'enseignement de francais et de mathematiques du cycle 4",
    organisme: "Ministere de l'Education nationale — Bulletin officiel n° 10",
    url: 'https://www.education.gouv.fr/bo/2026/Hebdo10/MENE2602912A',
    date_publication: '2026-02-18',
    date_maj: '2026-03-05',
    date_consultation: '2026-08-08',
    session_concernee: 'a confirmer',
    statut: 'a_confirmer',
    resume:
      "Arrete du 18 fevrier 2026. Le calendrier d'entree en vigueur (5e en 2026, 4e en 2027, 3e en 2028) n'a PAS pu etre verifie sur la source primaire : la page renvoie HTTP 403. Tant qu'il n'est pas confirme, le dispositif ne s'appuie sur aucune de ses dispositions.",
  },
];

/* ------------------------------------------------------------------ */
/*  5. Regles officielles chiffrees                                   */
/* ------------------------------------------------------------------ */

export const REGLES_OFFICIELLES = [
  ['FR_DUREE', 'brevet_francais', "Duree de l'epreuve de francais", '3 heures', null, 'officiel',
   'BO_MENE2515977N', "Duree de l'epreuve : 3 heures", '2026+'],
  ['FR_TOTAL', 'brevet_francais', 'Bareme total, ramene sur 20', '100 points', 100, 'officiel',
   'BO_MENE2515977N',
   "Les exercices sont assortis d'un bareme totalisant 100 points, indique dans le sujet. La note obtenue est ensuite ramenee sur 20 pour le calcul de la moyenne.", '2026+'],
  ['FR_TEXTE', 'brevet_francais', 'Travail sur le texte litteraire et, eventuellement, sur une image', '50 points', 50, 'officiel',
   'BO_MENE2515977N',
   'Travail sur le texte litteraire et, eventuellement, sur une image (50 points - 1 heure et 10 minutes)', '2026+'],
  ['FR_DICTEE', 'brevet_francais', 'Dictee', '10 points', 10, 'officiel',
   'BO_MENE2515977N', 'Dictee (10 points - 20 minutes)', '2026+'],
  ['FR_DICTEE_LONGUEUR', 'brevet_francais', 'Longueur du texte dicte, serie generale', '600 signes environ', 600, 'officiel',
   'BO_MENE2515977N',
   "Un texte de 600 signes environ, en lien avec l'oeuvre, est dicte aux candidats de la serie generale.", '2026+'],
  ['FR_REDACTION', 'brevet_francais', 'Redaction', '40 points', 40, 'officiel',
   'BO_MENE2515977N', 'Redaction (40 points - 1 heure et 30 minutes)', '2026+'],
  ['FR_REDACTION_CHOIX', 'brevet_francais', 'Deux sujets de redaction au choix', 'reflexion | imagination', null, 'officiel',
   'BO_MENE2515977N',
   "Deux sujets au choix sont proposes aux candidats : un sujet de reflexion et un sujet d'imagination.", '2026+'],
  ['FR_REECRITURE', 'brevet_francais', 'Reecriture : cinq ou dix formes, bareme specifique aux erreurs de copie', '5 ou 10 formes', null, 'officiel',
   'BO_MENE2515977N',
   "...de maniere a obtenir cinq ou dix formes modifiees dans la copie de l'eleve. Les erreurs de pure copie ne portant pas sur les formes a modifier sont prises en compte dans l'evaluation selon un bareme specifique.", '2026+'],
  ['FR_DICTIONNAIRE', 'brevet_francais', 'Dictionnaire autorise pour la redaction', 'autorise', null, 'officiel',
   'BO_MENE2515977N',
   "Les candidats ont le droit, pour cette partie d'epreuve, de consulter un dictionnaire de langue francaise ou un dictionnaire bilingue.", '2026+'],

  ['MA_DUREE', 'brevet_mathematiques', "Duree de l'epreuve de mathematiques", '2 heures', null, 'officiel',
   'BO_MENE2515977N', "Duree de l'epreuve : 2 heures", '2026+'],
  ['MA_TOTAL', 'brevet_mathematiques', 'Note totale', '20 points', 20, 'officiel',
   'BO_MENE2515977N', "L'epreuve est notee sur 20.", '2026+'],
  ['MA_AUTOMATISMES', 'brevet_mathematiques', 'Partie 1 - Automatismes', '6 points, 20 minutes', 6, 'officiel',
   'BO_MENE2515977N', 'Partie 1 - Automatismes : 6 points - 20 minutes', '2026+'],
  ['MA_RAISONNEMENT', 'brevet_mathematiques', 'Partie 2 - Raisonnement et resolution de problemes', '14 points, 1 h 40', 14, 'officiel',
   'BO_MENE2515977N',
   'Partie 2 - Raisonnement et resolution de problemes : 14 points - 1 heure et 40 minutes.', '2026+'],
  ['MA_REDACTION', 'brevet_mathematiques', 'Qualite de la redaction', '2 points', 2, 'officiel',
   'BO_MENE2515977N',
   "L'evaluation doit prendre en compte la clarte et la precision des raisonnements ainsi que, plus largement, la qualite de la redaction qui sera evaluee sur 2 points.", '2026+'],
  ['MA_REDACTION_INCLUSE', 'brevet_mathematiques', 'Les 2 points de redaction sont COMPRIS dans les 14', 'incluse', null, 'officiel_par_deduction',
   'BO_MENE2515977N',
   'Deduction arithmetique : la note de service place la phrase dans la partie 2 et fixe le total a 20 pour 6 + 14. Les 2 points ne peuvent donc pas s\'ajouter au-dessus des 14. CORROBORE par les deux sujets zero serie generale : leurs exercices de partie 2 totalisent 12 points (3+3+3+3 pour le sujet A, 3+2+4,5+2,5 pour le sujet B), les 2 points de redaction completant les 14 annonces.', '2026+'],
  ['MA_CALCULATRICE', 'brevet_mathematiques', 'Calculatrice', 'autorisee en partie 2 seulement', null, 'officiel',
   'BO_MENE2515977N', "La calculatrice n'est autorisee que sur la partie 2.", '2026+'],
  ['MA_BROUILLON', 'brevet_mathematiques', 'Brouillon', "autorise sur l'ensemble de l'epreuve", null, 'officiel',
   'BO_MENE2515977N', "Le brouillon est autorise sur l'ensemble de l'epreuve.", '2026+'],
  ['MA_ESSAIS', 'brevet_mathematiques', 'Prise en compte des essais et demarches non abouties', 'obligatoire', null, 'officiel',
   'BO_MENE2515977N',
   'Doivent etre pris en compte les essais et les demarches engagees, meme non abouties.', '2026+'],
  ['MA_JUSTIFICATION', 'brevet_mathematiques', 'Justification des reponses', 'sauf indication contraire', null, 'officiel',
   'BO_MENE2515977N',
   'Le sujet precise que toutes les reponses doivent etre justifiees sauf si une indication contraire est donnee.', '2026+'],
  ['MA_EXERCICES_INDEPENDANTS', 'brevet_mathematiques', 'Exercices independants', 'oui', null, 'officiel',
   'BO_MENE2515977N',
   "Le sujet est constitue d'exercices qui doivent pouvoir etre traites par le candidat independamment les uns des autres.", '2026+'],
  ['MA_COMPETENCES', 'brevet_mathematiques', 'Competences mobilisees', 'chercher, modeliser, representer, raisonner, calculer, communiquer', null, 'officiel',
   'BO_MENE2515977N',
   'les candidats sont amenes a mobiliser les competences chercher, modeliser, representer, raisonner, calculer et communiquer.', '2026+'],

  ['FR_SOUS_PARTIES', 'brevet_francais', 'Sous-parties du bloc de 50 points', 'comprehension 32 + grammaire 18', null, 'complementaire',
   'SUJETS_ZERO_2026_SG',
   'Le sujet zero serie generale intitule "I. Comprehension et competences d\'interpretation (32 points)" et "II. Grammaire et competences linguistiques (18 points)". La note de service ne fixe pas cette repartition : elle est propre au sujet.', '2026'],
  ['FR_REECRITURE_POIDS', 'brevet_francais', 'Poids de la reecriture dans un sujet reel', '10 points sur les 18 de grammaire', 10, 'complementaire',
   'SUJETS_ZERO_2026_SG',
   'Question 10 du sujet zero : "Reecrivez le passage suivant en remplacant << je >> par << nous >>. (10 points)". La note de service ne fixe pas ce poids : il est propre au sujet.', '2026'],
  ['MA_AUTOMATISMES_NOMBRE', 'brevet_mathematiques', 'Nombre d\'items d\'automatismes dans un sujet reel', '9 questions pour 6 points', 9, 'complementaire',
   'SUJETS_ZERO_2026_SG',
   'Les deux sujets zero serie generale comportent 9 questions d\'automatismes. Le sujet B chiffre explicitement les questions 7, 8 et 9 a 1 point chacune. La note de service ne fixe aucun nombre d\'items.', '2026'],

  ['PROGRAMME_2027', 'commun', 'Programme de reference a partir de la session 2027', 'programme de la classe de troisieme', null, 'officiel',
   'BO_MENE2515977N',
   'declinees par le programme de francais de cycle 4 (ou de troisieme a partir de la session 2027)', '2027+'],
  ['SERIE', 'commun', 'Serie couverte par ce dispositif', 'generale', null, 'officiel',
   'BO_MENE2515977N',
   'La note de service distingue serie generale et serie professionnelle. Ce dispositif ne couvre que la serie generale.', '2026+'],
  ['PROGRAMME_NOUVEAU_CYCLE4', 'commun', "Calendrier des nouveaux programmes de cycle 4", null, null, 'a_confirmer',
   'BO_PROGRAMMES_CYCLE4_2026',
   '', 'a confirmer'],
];

/* ------------------------------------------------------------------ */
/*  6. Parametres d'exploitation                                      */
/* ------------------------------------------------------------------ */

export const PARAMETRES = [
  {
    matiere: 'commun',
    cle: 'seuils_relecture',
    valeur: { seuils: [10], tolerance: 0.5 },
    commentaire:
      "Notes proches d'un seuil administratif : une copie a 9,5 ou 10,5 sur 20 declenche une alerte informative. 10 est le seuil d'obtention du diplome.",
  },
  {
    matiere: 'commun',
    cle: 'ecart_evaluations_significatif',
    valeur: { points: 2 },
    commentaire:
      "Au-dela de 2 points d'ecart entre deux evaluations d'une meme copie, la reference humaine n'est pas presentee comme objective.",
  },
  {
    matiere: 'commun',
    cle: 'seuil_confiance',
    valeur: { valeur: 0.85 },
    commentaire: 'Sous ce seuil, la correction part systematiquement en validation humaine.',
  },
  {
    matiere: 'brevet_francais',
    cle: 'seuil_decalage_ocr_dictee',
    valeur: { ecarts_consecutifs: 6 },
    commentaire:
      'Serie d\'ecarts consecutifs au-dela de laquelle on suspecte un decalage de transcription plutot qu\'une avalanche de fautes.',
  },
  {
    matiere: 'brevet_mathematiques',
    cle: 'qualite_redaction_max',
    valeur: { points: 2, incluse_dans_partie_2: true },
    commentaire:
      'Les 2 points de qualite redactionnelle sont compris dans les 14 de la partie 2. brevet_verifier() refuse un bareme qui les ajouterait au-dessus.',
  },
];
