#!/usr/bin/env node
// =====================================================================
//  REMETTRE LES ACCENTS DANS LES GRILLES DE NOTATION
//
//    node scripts/accents-grilles.mjs            (rapport seul, n'ecrit rien)
//    node scripts/accents-grilles.mjs --apply    (ecrit en base)
//    node scripts/accents-grilles.mjs --diff     (montre tous les textes changes)
//
//  POURQUOI. Le SQL d'installation des matieres est volontairement en ASCII
//  pur : l'editeur SQL de Supabase abime les accents colles depuis un Mac.
//  Les descriptions de paliers sont donc arrivees en base sans accents
//  (« Maitrise complete : reponse precise »), et c'est ce qu'un professeur
//  lit a l'ecran. On les repare ici, une fois, par l'API REST — qui, elle,
//  accepte l'UTF-8 sans broncher.
//
//  COMMENT. Mot a mot, avec un dictionnaire EXPLICITE. Aucune heuristique :
//  un mot absent du dictionnaire n'est pas touche. Les mots ambigus en sont
//  volontairement absents — « a » (a / a), « ou » (ou / ou), « note »
//  (note / note) : un accent pose au hasard change le sens.
//
//  La casse et la ponctuation sont conservees : « Maitrise » redevient
//  « Maitrise » avec sa majuscule.
//
//  IDEMPOTENT : rejouable sans risque. Un texte deja accentue ne bouge plus.
//  Ecrit une sauvegarde horodatee avant toute modification.
// =====================================================================

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';

const ROOT = resolve(dirname(new URL(import.meta.url).pathname), '..');
const APPLIQUER = process.argv.includes('--apply');
const MONTRER_DIFF = process.argv.includes('--diff');

/* ------------------------------------------------------------------ */
/*  Le dictionnaire                                                    */
/* ------------------------------------------------------------------ */

/**
 * Mot sans accent → mot accentue. Tout en minuscules ; la casse d'origine est
 * reappliquee ensuite.
 *
 * Ne PAS ajouter ici un mot dont la forme sans accent existe aussi en
 * francais. Les absents volontaires : a, ou, note(s), compte, cote, juge,
 * pose, nuance, mode, tache, sur, du, la, des.
 */
const ACCENTS = {
  // --- Deuxième relecture du diff ---
  unite: 'unité',
  unites: 'unités',
  brievement: 'brièvement',
  approchee: 'approchée',
  analysee: 'analysée',
  algebre: 'algèbre',
  concretes: 'concrètes',
  desequilibree: 'déséquilibrée',
  difference: 'différence',
  entieres: 'entières',
  equilibrer: 'équilibrer',
  equilibres: 'équilibres',
  etudiees: 'étudiées',
  fidelement: 'fidèlement',
  fidelite: 'fidélité',
  interpretee: 'interprétée',
  interpretes: 'interprétés',
  inventee: 'inventée',
  "l'originalite": "l'originalité",
  laissee: 'laissée',
  majorite: 'majorité',
  mathematique: 'mathématique',
  mobilisees: 'mobilisées',
  notee: 'notée',
  notees: 'notées',
  reelles: 'réelles',
  reels: 'réels',
  refuter: 'réfuter',
  relevee: 'relevée',
  reperables: 'repérables',
  repetitive: 'répétitive',
  reponses: 'réponses',
  resolutions: 'résolutions',
  resumer: 'résumer',
  situees: 'situées',
  tiree: 'tirée',
  variete: 'variété',
  verifies: 'vérifiés',
  convoques: 'convoqués',
  donnes: 'donnés',
  reduits: 'réduits',
  justifiees: 'justifiées',
  expliquees: 'expliquées',
  articules: 'articulés',
  eclaircies: 'éclaircies',
  tranchees: 'tranchées',
  maillons: 'maillons',
  // --- Noms en -té : jamais ambigus ---
  validite: 'validité',
  qualite: 'qualité',
  capacite: 'capacité',
  securite: 'sécurité',
  quantite: 'quantité',
  diversite: 'diversité',
  autorite: 'autorité',
  clarte: 'clarté',
  fluidite: 'fluidité',
  solidite: 'solidité',
  exhaustivite: 'exhaustivité',
  moitie: 'moitié',
  propriete: 'propriété',
  probabilite: 'probabilité',
  homogeneite: 'homogénéité',
  reproductibilite: 'reproductibilité',
  orthonormalite: 'orthonormalité',
  colinearite: 'colinéarité',
  orthogonalite: 'orthogonalité',
  coplanarite: 'coplanarité',
  reconstituee: 'reconstituée',
  // --- Ajouts après relecture du diff ---
  etre: 'être',
  idee: 'idée',
  idees: 'idées',
  materiel: 'matériel',
  difficulte: 'difficulté',
  difficultes: 'difficultés',
  eloignee: 'éloignée',
  creer: 'créer',
  noye: 'noyé',
  noyee: 'noyée',
  valorisee: 'valorisée',
  exigee: 'exigée',
  depasse: 'dépasse',
  depassee: 'dépassée',
  rattachee: 'rattachée',
  replacee: 'replacée',
  selection: 'sélection',
  selectionnee: 'sélectionnée',
  eloigne: 'éloigné',
  redigees: 'rédigées',
  reussite: 'réussite',
  reduites: 'réduites',
  reduite: 'réduite',
  rincage: 'rinçage',
  epi: 'EPI',
  numerote: 'numéroté',
  deduite: 'déduite',
  espece: 'espèce',
  regle: 'règle',
  adequat: 'adéquat',
  specifique: 'spécifique',
  // --- Niveaux et jugements ---
  tres: 'très',
  maitrise: 'maîtrise',
  maitrisees: 'maîtrisées',
  complete: 'complète',
  completes: 'complètes',
  complet: 'complet',
  incomplete: 'incomplète',
  precis: 'précis',
  precise: 'précise',
  precises: 'précises',
  precisement: 'précisément',
  precision: 'précision',
  precisees: 'précisées',
  preciser: 'préciser',
  imprecis: 'imprécis',
  element: 'élément',
  elements: 'éléments',
  reponse: 'réponse',
  repondre: 'répondre',
  repond: 'répond',
  repondant: 'répondant',
  comprehension: 'compréhension',
  comprehensible: 'compréhensible',
  redaction: 'rédaction',
  rediger: 'rédiger',
  redigee: 'rédigée',
  reflexion: 'réflexion',
  resultat: 'résultat',
  resultats: 'résultats',
  reference: 'référence',
  references: 'références',
  referentiel: 'référentiel',
  etapes: 'étapes',
  etape: 'étape',
  donnees: 'données',
  donnee: 'donnée',
  meme: 'même',
  these: 'thèse',
  theses: 'thèses',
  problematique: 'problématique',
  problematisation: 'problématisation',
  probleme: 'problème',
  mathematiques: 'mathématiques',
  demonstration: 'démonstration',
  demontre: 'démontre',
  demontree: 'démontrée',
  demontrees: 'démontrées',
  demontrer: 'démontrer',
  enonces: 'énoncés',
  enoncer: 'énoncer',
  enoncees: 'énoncées',
  enoncant: 'énonçant',
  "l'enonce": "l'énoncé",
  relies: 'reliés',
  reliees: 'reliées',
  reliee: 'reliée',
  relier: 'relier',
  pensee: 'pensée',
  posee: 'posée',
  posees: 'posées',
  identifiee: 'identifiée',
  identifies: 'identifiés',
  justifiee: 'justifiée',
  justifies: 'justifiés',
  justesse: 'justesse',
  nuancee: 'nuancée',
  nuances: 'nuances',
  coherent: 'cohérent',
  coherente: 'cohérente',
  coherence: 'cohérence',
  interpretation: 'interprétation',
  "d'interpretation": "d'interprétation",
  interprete: 'interprète',
  interpreter: 'interpréter',
  "l'interpreter": "l'interpréter",
  repere: 'repère',
  reperes: 'repères',
  reperer: 'repérer',
  reperees: 'repérées',
  reperage: 'repérage',
  generale: 'générale',
  generique: 'générique',
  methode: 'méthode',
  caractere: 'caractère',
  regles: 'règles',
  systematique: 'systématique',
  systematiques: 'systématiques',
  represente: 'représente',
  representer: 'représenter',
  representation: 'représentation',
  representations: 'représentations',
  "l'etude": "l'étude",
  verifiee: 'vérifiée',
  verifiees: 'vérifiées',
  verifier: 'vérifier',
  developpes: 'développés',
  developpement: 'développement',
  strategie: 'stratégie',
  critere: 'critère',
  criteres: 'critères',
  exactitude: 'exactitude',
  "l'exactitude": "l'exactitude",
  consequence: 'conséquence',
  hypotheses: 'hypothèses',
  hypothese: 'hypothèse',
  coeur: 'cœur',
  oeuvres: 'œuvres',
  uvre: 'œuvre',
  evenements: 'événements',
  pertinence: 'pertinence',
  mecanique: 'mécanique',
  mecanismes: 'mécanismes',
  numerique: 'numérique',
  litteral: 'littéral',
  litterale: 'littérale',
  litteraire: 'littéraire',
  modeles: 'modèles',
  modele: 'modèle',
  modelisation: 'modélisation',
  modeliser: 'modéliser',
  preuve: 'preuve',
  nommes: 'nommés',
  nommee: 'nommée',
  nommees: 'nommées',
  objectif: 'objectif',
  "l'objectif": "l'objectif",
  exploitee: 'exploitée',
  experimentale: 'expérimentale',
  experimental: 'expérimental',
  ecart: 'écart',
  "d'ecart": "d'écart",
  degagee: 'dégagée',
  ecrire: 'écrire',
  ecrit: 'écrit',
  ecrite: 'écrite',
  "l'ecrit": "l'écrit",
  "l'ecriture": "l'écriture",
  ecriture: 'écriture',
  employes: 'employés',
  employee: 'employée',
  employees: 'employées',
  explorees: 'explorées',
  "s'arrete": "s'arrête",
  triee: 'triée',
  triees: 'triées',
  engagee: 'engagée',
  calculer: 'calculer',
  designe: 'désigne',
  probabilites: 'probabilités',
  expliques: 'expliqués',
  appuyee: 'appuyée',
  echelle: 'échelle',
  echelles: 'échelles',
  notionnelles: 'notionnelles',
  exploite: 'exploite',
  "l'expression": "l'expression",
  "s'approprier": "s'approprier",
  grandeurs: 'grandeurs',
  economique: 'économique',
  presente: 'présente',
  presentes: 'présentes',
  presence: 'présence',
  presentation: 'présentation',
  menee: 'menée',
  menes: 'menés',
  reaction: 'réaction',
  discutee: 'discutée',
  discutees: 'discutées',
  production: 'production',
  recopies: 'recopiés',
  recopiee: 'recopiée',
  recopiees: 'recopiées',
  recopier: 'recopier',
  entierement: 'entièrement',
  partielles: 'partielles',
  quantitatif: 'quantitatif',
  "l'argumentation": "l'argumentation",
  approximatif: 'approximatif',
  approximatifs: 'approximatifs',
  approximatives: 'approximatives',
  jaugee: 'jaugée',
  especes: 'espèces',
  evoquee: 'évoquée',
  utilisee: 'utilisée',
  disponible: 'disponible',
  "l'eau": "l'eau",
  "l'acide": "l'acide",
  adaptees: 'adaptées',
  adaptee: 'adaptée',
  calculee: 'calculée',
  prevu: 'prévu',
  prevues: 'prévues',
  "n'indique": "n'indique",
  "d'exploitable": "d'exploitable",
  realisation: 'réalisation',
  realiser: 'réaliser',
  relevees: 'relevées',
  organisee: 'organisée',
  organisees: 'organisées',
  entames: 'entamés',
  isolees: 'isolées',
  depart: 'départ',
  explique: 'explique',
  explications: 'explications',
  estimee: 'estimée',
  irregulieres: 'irrégulières',
  tenues: 'tenues',
  chapitre: 'chapitre',
  attendues: 'attendues',
  factuelles: 'factuelles',
  anachronismes: 'anachronismes',
  anachroniques: 'anachroniques',
  progresse: 'progresse',
  "l'exige": "l'exige",
  illustrent: 'illustrent',
  ressortir: 'ressortir',
  essentielles: 'essentielles',
  retenues: 'retenues',
  "l'organisation": "l'organisation",
  regroupement: 'regroupement',
  descriptifs: 'descriptifs',
  ponctuels: 'ponctuels',
  traduisent: 'traduisent',
  admissibles: 'admissibles',
  arbitraires: 'arbitraires',
  localisation: 'localisation',
  localisations: 'localisations',
  gravement: 'gravement',
  orientation: 'orientation',
  apparente: 'apparente',
  oublis: 'oublis',
  souleve: 'soulève',
  immediate: 'immédiate',
  interroge: 'interroge',
  amorce: 'amorce',
  amorcee: 'amorcée',
  avancee: 'avancée',
  avancer: 'avancer',
  apparaissent: 'apparaissent',
  concept: 'concept',
  central: 'central',
  distingues: 'distingués',
  distinguee: 'distinguée',
  distinguer: 'distinguer',
  distinction: 'distinction',
  examinees: 'examinées',
  serieusement: 'sérieusement',
  exposees: 'exposées',
  "d'auteur": "d'auteur",
  "d'auteurs": "d'auteurs",
  "l'auteur": "l'auteur",
  atteindre: 'atteindre',
  opposees: 'opposées',
  "l'orner": "l'orner",
  plaquee: 'plaquée',
  articulee: 'articulée',
  articulees: 'articulées',
  articulation: 'articulation',
  articulations: 'articulations',
  integrees: 'intégrées',
  amene: 'amène',
  nait: 'naît',
  "l'insuffisance": "l'insuffisance",
  precedente: 'précédente',
  precede: 'précède',
  assumee: 'assumée',
  veritables: 'véritables',
  progressif: 'progressif',
  progressive: 'progressive',
  molecules: 'molécules',
  temoins: 'témoins',
  deductions: 'déductions',
  deduction: 'déduction',
  valides: 'valides',
  chaine: 'chaîne',
  "d'inequations": "d'inéquations",
  primitives: 'primitives',
  "d'integrales": "d'intégrales",
  simplifiees: 'simplifiées',
  fractions: 'fractions',
  evolution: 'évolution',
  phenomene: 'phénomène',
  extremum: 'extremum',
  manipules: 'manipulés',
  manipulees: 'manipulées',
  probabilistes: 'probabilistes',
  "l'univers": "l'univers",
  aleatoire: 'aléatoire',
  definie: 'définie',
  definir: 'définir',
  defini: 'défini',
  definis: 'définis',
  definitions: 'définitions',
  commentee: 'commentée',
  independance: 'indépendance',
  evenement: 'événement',
  "d'application": "d'application",
  incompatibles: 'incompatibles',
  coefficients: 'coefficients',
  binomiaux: 'binomiaux',
  binomiale: 'binomiale',
  esperance: 'espérance',
  calculatrice: 'calculatrice',
  "l'intervalle": "l'intervalle",
  fantaisistes: 'fantaisistes',
  parametrique: 'paramétrique',
  parametres: 'paramètres',
  cartesienne: 'cartésienne',
  vectorielle: 'vectorielle',
  melangees: 'mélangées',
  converties: 'converties',
  appartenance: 'appartenance',
  affirmees: 'affirmées',
  "d'apres": "d'après",
  confondus: 'confondus',
  confondues: 'confondues',
  systemes: 'systèmes',
  systeme: 'système',
  equations: 'équations',
  "d'equations": "d'équations",
  distances: 'distances',
  projetes: 'projetés',
  orthogonaux: 'orthogonaux',
  aires: 'aires',
  racines: 'racines',
  arrondies: 'arrondies',
  arrondis: 'arrondis',
  arrondi: 'arrondi',
  prematurement: 'prématurément',
  soustraites: 'soustraites',
  "l'envers": "l'envers",
  scalaire: 'scalaire',
  scalaires: 'scalaires',
  geometrique: 'géométrique',
  geographique: 'géographique',
  geopolitique: 'géopolitique',
  proprietes: 'propriétés',
  vecteurs: 'vecteurs',
  vecteur: 'vecteur',
  conclusions: 'conclusions',
  justifications: 'justifications',
  justification: 'justification',
  algorithmique: 'algorithmique',
  algorithme: 'algorithme',
  "d'arret": "d'arrêt",
  renvoyee: 'renvoyée',
  principale: 'principale',
  principales: 'principales',
  secondaires: 'secondaires',
  secondaire: 'secondaire',
  statut: 'statut',
  decoupage: 'découpage',
  ruptures: 'ruptures',
  presupposes: 'présupposés',
  presuppose: 'présuppose',
  philosophique: 'philosophique',
  philosophiques: 'philosophiques',
  philosophie: 'philosophie',
  ponctuation: 'ponctuation',
  exterieures: 'extérieures',
  restituees: 'restituées',
  restitution: 'restitution',
  perdue: 'perdue',
  perdre: 'perdre',
  imposees: 'imposées',
  procedes: 'procédés',
  dimensions: 'dimensions',
  essentielle: 'essentielle',
  essentiellement: 'essentiellement',
  dominante: 'dominante',
  incompris: 'incompris',
  distincts: 'distincts',
  convaincante: 'convaincante',
  cataloguer: 'cataloguer',
  catalogue: 'catalogue',
  analytique: 'analytique',
  dialectique: 'dialectique',
  personnages: 'personnages',
  conducteur: 'conducteur',
  temporelles: 'temporelles',
  temporelle: 'temporelle',
  "l'illustrer": "l'illustrer",
  vaguement: 'vaguement',
  physiques: 'physiques',
  initiales: 'initiales',
  inconnue: 'inconnue',
  "l'inconnue": "l'inconnue",
  "s'applique": "s'applique",
  manquantes: 'manquantes',
  manquante: 'manquante',
  suivies: 'suivies',
  tabulaire: 'tabulaire',
  etablie: 'établie',
  etablir: 'établir',
  aberrant: 'aberrant',
  conservees: 'conservées',
  negative: 'négative',
  superieure: 'supérieure',
  constantes: 'constantes',
  deja: 'déjà',
  jugee: 'jugée',
  ininterpretable: 'ininterprétable',
  "l'exploiter": "l'exploiter",
  prelevement: 'prélèvement',
  prelevements: 'prélèvements',
  prelevees: 'prélevées',
  prelever: 'prélever',
  hierarchises: 'hiérarchisés',
  hierarchisees: 'hiérarchisées',
  hierarchisation: 'hiérarchisation',
  ignores: 'ignorés',
  employer: 'employer',
  recitees: 'récitées',
  recitee: 'récitée',
  periode: 'période',
  frequence: 'fréquence',
  frequentes: 'fréquentes',
  "s'enchainent": "s'enchaînent",
  enchainer: 'enchaîner',
  enchainement: 'enchaînement',
  prouvent: 'prouvent',
  "d'informations": "d'informations",
  "d'ordre": "d'ordre",
  conversion: 'conversion',
  conversions: 'conversions',
  decisif: 'décisif',
  conclu: 'conclu',
  "d'unite": "d'unité",
  telegraphique: 'télégraphique',
  chimique: 'chimique',
  mesuree: 'mesurée',
  pipette: 'pipette',
  burette: 'burette',
  fiole: 'fiole',
  conductimetre: 'conductimètre',
  spectrophotometre: 'spectrophotomètre',
  recipient: 'récipient',
  recherchee: 'recherchée',
  reproduit: 'reproduit',
  operatoires: 'opératoires',
  operatoire: 'opératoire',
  ordonner: 'ordonner',
  operations: 'opérations',
  concentrations: 'concentrations',
  concentration: 'concentration',
  agitation: 'agitation',
  temperature: 'température',
  reproductible: 'reproductible',
  delicats: 'délicats',
  "l'equivalence": "l'équivalence",
  equivalence: 'équivalence',
  anticipes: 'anticipés',
  anticipee: 'anticipée',
  eleve: 'élève',
  devrait: 'devrait',
  deviner: 'deviner',
  desordre: 'désordre',
  chiffree: 'chiffrée',
  chiffrees: 'chiffrées',
  chiffrer: 'chiffrer',
  chiffres: 'chiffres',
  chiffre: 'chiffre',
  incertitudes: 'incertitudes',
  incertitude: 'incertitude',
  "l'incertitude": "l'incertitude",
  "d'incertitude": "d'incertitude",
  imposees2: 'imposées',
  hotte: 'hotte',
  acides: 'acides',
  "d'ou": "d'où",
  precaution: 'précaution',
  precautions: 'précautions',
  exigent: 'exigent',
  verser: 'verser',
  porter: 'porter',
  gants: 'gants',
  fera: 'fera',
  calculable: 'calculable',
  vraisemblance: 'vraisemblance',
  gestes: 'gestes',
  geste: 'geste',
  plausible: 'plausible',
  alternative: 'alternative',
  ecartee: 'écartée',
  observable: 'observable',
  conduits: 'conduits',
  moyenne: 'moyenne',
  brut: 'brut',
  graduee: 'graduée',
  decrire: 'décrire',
  decrit: 'décrit',
  decrite: 'décrite',
  appareils: 'appareils',
  appareil: 'appareil',
  determiner: 'déterminer',
  juxtaposees: 'juxtaposées',
  juxtaposition: 'juxtaposition',
  fondee: 'fondée',
  decoule: 'découle',
  envisagees: 'envisagées',
  envisagee: 'envisagée',
  choisies: 'choisies',
  "d'origine": "d'origine",
  lacunaire: 'lacunaire',
  lacunaires: 'lacunaires',
  lacunes: 'lacunes',
  evidence: 'évidence',
  ailleurs: 'ailleurs',
  comparaison: 'comparaison',
  controler: 'contrôler',
  controle: 'contrôle',
  significatifs: 'significatifs',
  puissances: 'puissances',
  signes: 'signes',
  proprement: 'proprement',
  locales: 'locales',
  "l'execution": "l'exécution",
  executer: 'exécuter',
  executable: 'exécutable',
  application: 'application',
  demarche: 'démarche',
  formules: 'formules',
  formule: 'formule',
  poses: 'posés',
  implicites: 'implicites',
  implicite: 'implicite',
  restent: 'restent',
  schema: 'schéma',
  schemas: 'schémas',
  legendes: 'légendes',
  flechage: 'fléchage',
  "d'ambiguite": "d'ambiguïté",
  historique: 'historique',
  selectionnee: 'sélectionnée',
  selection: 'sélection',
  porteuse: 'porteuse',
  guider: 'guider',
  "l'exemple": "l'exemple",
  "l'argument": "l'argument",
  cites: 'cités',
  citees: 'citées',
  citer: 'citer',
  citations: 'citations',
  citation: 'citation',
  plafond: 'plafond',
  scientifiques: 'scientifiques',
  scientifique: 'scientifique',
  contradiction: 'contradiction',
  issue: 'issue',
  lexique: 'lexique',
  difficile: 'difficile',
  difficilement: 'difficilement',
  dominant: 'dominant',
  remarques: 'remarques',
  constante: 'constante',
  majoritairement: 'majoritairement',
  effets: 'effets',
  paraphraser: 'paraphraser',
  paraphrase: 'paraphrase',
  riches: 'riches',
  globale: 'globale',
  globalement: 'globalement',
  silences: 'silences',
  rares: 'rares',
  transition: 'transition',
  transitions: 'transitions',
  faute: 'faute',
  negligences: 'négligences',
  accords: 'accords',
  constructions: 'constructions',
  survit: 'survit',
  correction: 'correction',
  decompte: 'décompte',
  marge: 'marge',
  prouve: 'prouve',
  passages: 'passages',
  destinataire: 'destinataire',
  majeur: 'majeur',
  majeures: 'majeures',
  pertinents: 'pertinents',
  pertinente: 'pertinente',
  pertinentes: 'pertinentes',
  commentaire: 'commentaire',
  eclairer: 'éclairer',
  enjeu: 'enjeu',
  "l'enjeu": "l'enjeu",
  enjeux: 'enjeux',
  propre: 'propre',
  tenue: 'tenue',
  portee: 'portée',
  explicites: 'explicites',
  explicitement: 'explicitement',
  produits: 'produits',
  terme: 'terme',
  termes: 'termes',
  nombre: 'nombre',
  nombres: 'nombres',
  theoremes: 'théorèmes',
  recurrence: 'récurrence',
  derivees: 'dérivées',
  moment: 'moment',
  "l'ensemble": "l'ensemble",
  rigueur: 'rigueur',
  rigoureux: 'rigoureux',
  rigoureuse: 'rigoureuse',
  rigoureusement: 'rigoureusement',
  facon: 'façon',
  dossier: 'dossier',
  maillon: 'maillon',
  nette: 'nette',
  demande: 'demande',
  questions: 'questions',
  plupart: 'plupart',
  noms: 'noms',
  cartographique: 'cartographique',
  visuelles: 'visuelles',
  visuel: 'visuel',
  langage: 'langage',
  titres: 'titres',
  titre: 'titre',
  croquis: 'croquis',
  emploi: 'emploi',
  cause: 'cause',
  vrac: 'vrac',
  contraintes: 'contraintes',
  sources: 'sources',
  fausse: 'fausse',
  fausses: 'fausses',
  faussent: 'faussent',
  donne: 'donne',
  condition: 'condition',
  conditions: 'conditions',
  dilution: 'dilution',
  volumes: 'volumes',
  volume: 'volume',
  clair: 'clair',
  claire: 'claire',
  claires: 'claires',
  cette: 'cette',
  support: 'support',
  objections: 'objections',
  objection: 'objection',
  attendus: 'attendus',
  attendue: 'attendue',
  travail: 'travail',
  croisement: 'croisement',
  premiere: 'première',
  physique: 'physique',
  symboles: 'symboles',
  tableau: 'tableau',
  elliptique: 'elliptique',
  lois: 'lois',
  loi: 'loi',
  domaine: 'domaine',
  hasard: 'hasard',
  argumentee: 'argumentée',
  argumentees: 'argumentées',
  argumentative: 'argumentative',
  argumentation: 'argumentation',
  rompt: 'rompt',
  choisir: 'choisir',
  leurs: 'leurs',
  totalement: 'totalement',
  totales: 'totales',
  total: 'total',
  identifier: 'identifier',
  identification: 'identification',
  identifiable: 'identifiable',
  paragraphe: 'paragraphe',
  paragraphes: 'paragraphes',
  lieux: 'lieux',
  lieu: 'lieu',
  suivi: 'suivi',
  incomplets: 'incomplets',
  incomplet: 'incomplet',
  partiellement: 'partiellement',
  conforme: 'conforme',
  conformes: 'conformes',
  soutenir: 'soutenir',
  soutenue: 'soutenue',
  formuler: 'formuler',
  formulee: 'formulée',
  formulation: 'formulation',
  formulations: 'formulations',
  rend: 'rend',
  rendant: 'rendant',
  rendu: 'rendu',
  celui: 'celui',
  celle: 'celle',
  reelle: 'réelle',
  reellement: 'réellement',
  conceptualisation: 'conceptualisation',
  conceptuel: 'conceptuel',
  concepts: 'concepts',
  "qu'affirmer": "qu'affirmer",
  tenus: 'tenus',
  racontes: 'racontés',
  inaboutis: 'inaboutis',
  souvent: 'souvent',
  "d'affirmations": "d'affirmations",
  "d'opinions": "d'opinions",
  affirmations: 'affirmations',
  affirmation: 'affirmation',
  mobilisee: 'mobilisée',
  mobiliser: 'mobiliser',
  mobilisation: 'mobilisation',
  sert: 'sert',
  necessaire: 'nécessaire',
  supplement: 'supplément',
  sobre: 'sobre',
  maladroite: 'maladroite',
  maladroites: 'maladroites',
  maladresses: 'maladresses',
  flottante: 'flottante',
  flottantes: 'flottantes',
  deficiente: 'déficiente',
  connecteur: 'connecteur',
  connecteurs: 'connecteurs',
  initialisation: 'initialisation',
  formes: 'formes',
  forme: 'forme',
  forment: 'forment',
  inventees: 'inventées',
  reconnaitre: 'reconnaître',
  traduction: 'traduction',
  traduite: 'traduite',
  traduire: 'traduire',
  conditionnelle: 'conditionnelle',
  intersection: 'intersection',
  conclure: 'conclure',
  conclut: 'conclut',
  conclus: 'conclus',
  figure: 'figure',
  seule: 'seule',
  seuls: 'seuls',
  seulement: 'seulement',
  car: 'car',
  sait: 'sait',
  vague: 'vague',
  vagues: 'vagues',
  raison: 'raison',
  raisonner: 'raisonner',
  raisonnement: 'raisonnement',
  continue: 'continue',
  quelle: 'quelle',
  "qu'une": "qu'une",
  "qu'il": "qu'il",
  "qu'ils": "qu'ils",
  "qu'elle": "qu'elle",
  "qu'elles": "qu'elles",
  "qu'on": "qu'on",
  ici: 'ici',
  apparait: 'apparaît',
  debut: 'début',
  fin: 'fin',
  graphique: 'graphique',
  repetees: 'répétées',
  locale: 'locale',
  limite: 'limite',
  limites: 'limites',
  illisible: 'illisible',
  inintelligible: 'inintelligible',
  lisible: 'lisible',
  lisibles: 'lisibles',
  mis: 'mis',
  mise: 'mise',
  mises: 'mises',
  valeur: 'valeur',
  valeurs: 'valeurs',
  absente: 'absente',
  absentes: 'absentes',
  absents: 'absents',
  absence: 'absence',
  absent: 'absent',
  traitement: 'traitement',
  style: 'style',
  plutot: 'plutôt',
  cherchee: 'cherchée',
  chercher: 'chercher',
  montage: 'montage',
  effet: 'effet',
  annoncees: 'annoncées',
  annoncee: 'annoncée',
  annonce: 'annonce',
  annoncer: 'annoncer',
  construits: 'construits',
  construites: 'construites',
  construit: 'construit',
  construction: 'construction',
  construire: 'construire',
  elles: 'elles',
  variables: 'variables',
  variable: 'variable',
  nomenclature: 'nomenclature',
  exactement: 'exactement',
  expliquer: 'expliquer',
  genent: 'gênent',
  gene: 'gêne',
  passer: 'passer',
  passage: 'passage',
  vaut: 'vaut',
  utile: 'utile',
  utiles: 'utiles',
  reformuler: 'reformuler',
  reformulee: 'reformulée',
  reformulation: 'reformulation',
  cet: 'cet',
  contre: 'contre',
  dit: 'dit',
  mouvement: 'mouvement',
  mouvements: 'mouvements',
  fait: 'fait',
  faits: 'faits',
  auteur: 'auteur',
  date: 'date',
  dates: 'dates',
  largement: 'largement',
  solide: 'solide',
  pleinement: 'pleinement',
  lorsqu: 'lorsqu',
  "lorsqu'elle": "lorsqu'elle",
  nombreuses: 'nombreuses',
  directrice: 'directrice',
  directeur: 'directeur',
  cles: 'clés',
  niveau: 'niveau',
  resolution: 'résolution',
  bilan: 'bilan',
  depasser: 'dépasser',
  tout: 'tout',
  toute: 'toute',
  toutes: 'toutes',
  surtout: 'surtout',
  reformulee2: 'reformulée',
  quand: 'quand',
  pourquoi: 'pourquoi',
  quel: 'quel',
  points: 'points',
  point: 'point',
  plus: 'plus',
  ligne: 'ligne',
  exercice: 'exercice',
  "l'exercice": "l'exercice",
  fil: 'fil',
  doit: 'doit',
  bloc: 'bloc',
  confuse: 'confuse',
  confus: 'confus',
  intention: 'intention',
  mesures: 'mesures',
  mesure: 'mesure',
  distance: 'distance',
  disciplinaire: 'disciplinaire',
  "l'information": "l'information",
  informations: 'informations',
  avant: 'avant',
  descriptive: 'descriptive',
  culture: 'culture',
  analyser: 'analyser',
  analyses: 'analyses',
  analyse: 'analyse',
  objets: 'objets',
  coordonnees: 'coordonnées',
  aux: 'aux',
  fluide: 'fluide',
  argument: 'argument',
  arguments: 'arguments',
  arrondi2: 'arrondi',
  moins: 'moins',
  partir: 'partir',
  communication: 'communication',
  spatiales: 'spatiales',
  parcours: 'parcours',
  vue: 'vue',
  simple: 'simple',
  contextualisation: 'contextualisation',
  prise: 'prise',
  prises: 'prises',
  pris: 'pris',
  partition: 'partition',
  lettre: 'lettre',
  rarement: 'rarement',
  quantificateurs: 'quantificateurs',
  utilisee2: 'utilisée',
  bout: 'bout',
  piste: 'piste',
  pistes: 'pistes',
  trace: 'trace',
  traces: 'traces',
  exploitables: 'exploitables',
  exploitable: 'exploitable',
  lors: 'lors',
  infructueuses: 'infructueuses',
  essayer: 'essayer',
  tester: 'tester',
  extraire: 'extraire',
  "s'engager": "s'engager",
  eux: 'eux',
  subsistent: 'subsistent',
  montre: 'montre',
  verrerie: 'verrerie',
  nommer: 'nommer',
  premier: 'premier',
  obstacle: 'obstacle',
  conjecture: 'conjecture',
};


/**
 * Les cas que le mot seul ne permet pas de trancher.
 *
 * « traite » est un verbe dans « la question se traite », un participe dans
 * « le sujet est traité ». Aucun dictionnaire mot a mot ne peut choisir : ces
 * corrections sont donc ecrites une par une, sur le morceau de phrase entier,
 * et appliquees APRES le dictionnaire.
 */
const EXCEPTIONS = [
  ['Le sujet traite doit être celui qui est pose', 'Le sujet traité doit être celui qui est posé'],
  ['le cours recite', 'le cours récité'],
  ['le sujet est traite comme', 'le sujet est traité comme'],
  ['la copie traite un sujet voisin', 'la copie traite un sujet voisin'],
  ['point de vue situe', 'point de vue situé'],
  ['décompte indique', 'décompte indiqué'],
  ['est ignore', 'est ignoré'],
  ['Format ignore', 'Format ignoré'],
  ['référence ignore', 'référence ignoré'],
  ['disponible est ignore', 'disponible est ignoré'],
  ['résultat livre brut', 'résultat livré brut'],
  ['aberrant conserve sans', 'aberrant conservé sans'],
  ['écart signale sans', 'écart signalé sans'],
  ['calcul est tente', 'calcul est tenté'],
  ['entache d', 'entaché d'],
  ['événement nomme', 'événement nommé'],
  ["principe n'est nomme", "principe n'est nommé"],
  ['conceptuel est employe', 'conceptuel est employé'],
  ['non argumente', 'non argumenté'],
  ['ordre argumente', 'ordre argumenté'],
  ['non justifie', 'non justifié'],
  ['verrerie justifie par', 'verrerie justifié par'],
  ["n'est pas verifie", "n'est pas vérifié"],
  ['grandeur verifie', 'grandeur vérifié'],
  ["n'est degage", "n'est dégagé"],
  ["l'enjeu est degage et rattache", "l'enjeu est dégagé et rattaché"],
  ['ou resume noye', 'ou résumé noyé'],
  ['raisonnement structure, appuye', 'raisonnement structuré, appuyé'],
  ['texte mobilise a bon escient', 'texte mobilisé à bon escient'],
  ['exemple cite sans être exploite', 'exemple cité sans être exploité'],
  ['nommer le procede', 'nommer le procédé'],
  ['un procede et un effet', 'un procédé et un effet'],
  ['non encadre ni enonce', 'non encadré ni énoncé'],
  ['résultat enonce', 'résultat énoncé'],
  ['son presuppose', 'son présupposé'],
  ['laisse de cote', 'laissé de côté'],
  ['Le releve seul', 'Le relevé seul'],
  ["l'objectif est recopie de", "l'objectif est recopié de"],
  ["l'énoncé est recopie", "l'énoncé est recopié"],
  ['texte recopie', 'texte recopié'],
  ['ce qui est demande', 'ce qui est demandé'],
  ['nombre de mots demande', 'nombre de mots demandé'],
  ['Aucun matériel nomme', 'Aucun matériel nommé'],
  ['ou resume noyé', 'ou résumé noyé'],
  ['conclusion qui resume au lieu', 'conclusion qui résume au lieu'],
  ['validité discute', 'validité discuté'],
  ['modèle discute', 'modèle discuté'],
  ['texte est cite sans être exploite', 'texte est cité sans être exploité'],
  ['conceptuel employe a bon escient', 'conceptuel employé à bon escient'],
  ['particulier teste ou conjecture', 'particulier testé ou conjecture'],
  ['releve organise, calculs', 'relevé organisé, calculs'],
  ['mouvement relie a la thèse', 'mouvement relié à la thèse'],
  ['résultat est compare', 'résultat est comparé'],
  ['analyses brièvement', 'analysés brièvement'],
  ['exemples analyses au service', 'exemples analysés au service'],
  ['exemples analyses', 'exemples analysés'],
  ['citee sans être exploitée', 'citée sans être exploitée'],
  ['inventée est sanctionnee', 'inventée est sanctionnée'],
  ['unité, exploite dans', 'unité, exploité dans'],
  ['le résultat interprète en contexte', 'le résultat interprété en contexte'],
];

/* ------------------------------------------------------------------ */
/*  Application                                                        */
/* ------------------------------------------------------------------ */

/** Rend a `accentue` la casse de `original` (Maitrise → Maîtrise). */
function memeCasse(original, accentue) {
  if (original === original.toUpperCase() && original.length > 1) return accentue.toUpperCase();
  if (original[0] === original[0].toUpperCase()) {
    return accentue[0].toUpperCase() + accentue.slice(1);
  }
  return accentue;
}

/**
 * Remet les accents dans un texte.
 *
 * Un texte qui en porte deja n'est pas touche : il a ete ecrit correctement,
 * et le dictionnaire n'a rien a y faire.
 */
export function accentuer(texte) {
  if (typeof texte !== 'string' || !texte) return texte;
  if (/[à-ÿÀ-Ÿ]/.test(texte)) return texte;
  let sortie = texte.replace(/[A-Za-z']+/g, (mot) => {
    const cible = ACCENTS[mot.toLowerCase()];
    return cible ? memeCasse(mot, cible) : mot;
  });
  // « a » isolé. Dans ces grilles c'est toujours la préposition « à » : le
  // corpus a été relu, il n'y contient ni « il a », ni « il y a », ni « n'a ».
  // La règle reste volontairement étroite — un « a » en début de phrase ou
  // suivi d'un participe passé n'est pas touché.
  sortie = sortie.replace(/(^|[^\S\n])a(?= )/g, (tout, avant, index) => {
    const suite = sortie.slice(index + tout.length + 1, index + tout.length + 30);
    // Seules formes du VERBE avoir qui pourraient apparaître un jour. « a la
    // question », « a une autre » sont bien la préposition : on les accentue.
    if (/^(été|pas |plus |jamais )/.test(suite)) return tout;
    return `${avant}à`;
  });
  for (const [avant, apres] of EXCEPTIONS) sortie = sortie.split(avant).join(apres);
  return sortie;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const env = {};
  for (const fichier of ['.env', '.env.local']) {
    let texte;
    try {
      texte = readFileSync(`${ROOT}/${fichier}`, 'utf8');
    } catch {
      continue;
    }
    for (const ligne of texte.split('\n')) {
      const m = ligne.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
      if (m && !env[m[1]]) env[m[1]] = m[2].replace(/^["']|["']$/g, '');
    }
  }
  const BASE = env.PIPELINE_SUPABASE_URL?.replace(/\/$/, '');
  const CLE = env.PIPELINE_SUPABASE_SERVICE_ROLE_KEY;
  if (!BASE || !CLE) {
    console.error('PIPELINE_SUPABASE_URL / PIPELINE_SUPABASE_SERVICE_ROLE_KEY absents.');
    process.exit(1);
  }
  const entetes = { apikey: CLE, Authorization: `Bearer ${CLE}`, 'Content-Type': 'application/json' };

  const grilles = await (
    await fetch(`${BASE}/rest/v1/rubrics?select=id,matiere,rubric_json`, { headers: entetes })
  ).json();

  const changements = [];
  const aEcrire = [];

  for (const g of grilles) {
    const avant = JSON.stringify(g.rubric_json ?? {});
    const rj = JSON.parse(avant);
    for (const c of rj.criteria ?? []) {
      for (const champ of ['name', 'description']) {
        const neuf = accentuer(c[champ]);
        if (neuf !== c[champ]) changements.push([g.id, champ, c[champ], neuf]);
        c[champ] = neuf;
      }
      for (const [palier, txt] of Object.entries(c.levels ?? {})) {
        const neuf = accentuer(txt);
        if (neuf !== txt) changements.push([g.id, `${c.code} ${palier}pt`, txt, neuf]);
        c.levels[palier] = neuf;
      }
    }
    if (JSON.stringify(rj) !== avant) aEcrire.push({ id: g.id, rubric_json: rj });
  }

  console.log(`\n${grilles.length} grilles lues · ${aEcrire.length} à modifier · ${changements.length} textes accentués\n`);
  if (MONTRER_DIFF) {
    for (const [id, ou, av, ap] of changements) {
      console.log(`── ${id} · ${ou}\n   - ${av}\n   + ${ap}`);
    }
  } else {
    for (const [id, ou, av, ap] of changements.slice(0, 12)) {
      console.log(`── ${id} · ${ou}\n   - ${av}\n   + ${ap}`);
    }
    if (changements.length > 12) console.log(`… et ${changements.length - 12} autres (--diff pour tout voir)`);
  }

  if (!APPLIQUER) {
    console.log('\nRien n’a été écrit. Relancer avec --apply.');
    process.exit(0);
  }

  const sauvegarde = `${ROOT}/sauvegardes/rubrics-avant-accents.json`;
  writeFileSync(sauvegarde, JSON.stringify(grilles, null, 1));
  console.log(`\nSauvegarde des grilles d’origine : ${sauvegarde}`);

  let ok = 0;
  for (const g of aEcrire) {
    const r = await fetch(`${BASE}/rest/v1/rubrics?id=eq.${encodeURIComponent(g.id)}`, {
      method: 'PATCH',
      headers: { ...entetes, Prefer: 'return=minimal' },
      body: JSON.stringify({ rubric_json: g.rubric_json }),
    });
    if (r.ok) ok += 1;
    else console.error(`  ✗ ${g.id} — HTTP ${r.status} ${(await r.text()).slice(0, 160)}`);
  }
  console.log(`\n${ok} / ${aEcrire.length} grilles mises à jour.`);
}
